version: "3.8"

services:
  app:
    build: .
    container_name: go-rate-limiter
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - prometheus
    environment:
      - REDIS_HOST=redis:6379
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
